version: 2.1

# set project level environment variables

orbs:
  buildalert: buildalert/demo@dev:0.0.2

jobs:
  build:
    docker:
      - image: circleci/python:latest
    steps:
      - run: echo 'hello world'


workflows:
  test:
    jobs:
      - buildalert/build:
          alert-threshold-seconds: 50000
          alert-threshold-max-builds-per-user: 0
          alert-threshold-max-builds-prev-minute: 0    
          circle-project-username-envvar: SLACK_MONITOR_CIRCLE_PROJECT_USERNAME
          circle-project-reponame-envvar: SLACK_MONITOR_CIRCLE_PROJECT_REPONAME
          circle-token-envvar: SLACK_MONITOR_CIRCLE_TOKEN
          slack-app-url-envvar: SLACK_MONITOR_SLACK_APP_URL
