version: 2.1

orbs:
  buildalert: buildalert/oss-build-alert@dev:0.0.2

workflows:
  monitor-every-minute:
    triggers:
      - schedule:
          cron: "* * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - buildalert/build:
          circle-project-org: 'annapamma'
          circle-project-reponame: 'sandbox'
          circle-token-envvar: SLACK_MONITOR_CIRCLE_TOKEN
          slack-app-url-envvar: SLACK_MONITOR_SLACK_APP_URL
          gh-token-env-var: SLACK_MONITOR_GH_TOKEN
          alert-threshold-seconds: 120
          alert-threshold-max-builds-per-user: 20
          alert-threshold-max-builds: 30
    health-check-trigger-every-minute:
      triggers:
        - schedule:
            cron: "* * * * *"
            filters:
              branches:
                only:
                  - master
      jobs:
        - buildalert/build:
            circle-project-org: 'annapamma'
            circle-project-reponame: 'sandbox'
            circle-token-envvar: SLACK_MONITOR_CIRCLE_TOKEN
            slack-app-url-envvar: SLACK_MONITOR_SLACK_APP_URL
            gh-token-env-var: SLACK_MONITOR_GH_TOKEN
            alert-threshold-seconds: 120
            alert-threshold-max-builds-per-user: 0
            alert-threshold-max-builds: 0
            siren-test: true
          # cancel-msg: 'The message you would like to post to cancelled PRs'
          # cancel-user-workflows: true
          # possible: trusted-users: enum 

# cost: https://circleci.com/api/v2/insights/gh/anna-buildalert/demo/workflows/monitor-every-minute
# ~3600 credits/day (~$2)

# follow multiple projects
# max builds should be across organization and not just individual repo
# one request to pull org, persist to workspace and check against workspace
# gh rate limits not an issue? GraphQL querying; charged for API interactions; abuse protection limits/reset time in headers?
# cost for POST? 

# how to verify that the setup works => monthly siren tests? really high thresholds?
# what is the roadmap for productionizing? 
