version: 2.1

# set project level environment variables

orbs:
  buildalert: buildalert/demo@dev:0.0.2

jobs:
  build:
    docker:
      - image: circleci/python:latest
    steps:
      - run: echo 'hello world'


workflows:
  test:
    jobs:
      - buildalert/build:
          alert-threshold-seconds: 50000
          alert-threshold-max-builds-per-user: 0
          alert-threshold-max-builds-prev-minute: 0    
          SLACK_MONITOR_CIRCLE_PROJECT_USERNAME_ENVVAR: SLACK_MONITOR_CIRCLE_PROJECT_USERNAME
          SLACK_MONITOR_CIRCLE_PROJECT_REPONAME_ENVVAR: SLACK_MONITOR_CIRCLE_PROJECT_REPONAME
          SLACK_MONITOR_CIRCLE_TOKEN_ENVVAR: SLACK_MONITOR_CIRCLE_TOKEN
          SLACK_MONITOR_SLACK_APP_URL_ENVVAR: SLACK_MONITOR_SLACK_APP_URL
